trigger:
  branches:
    include:
    - master
  paths:
    include:
    - environment_setup/arm-templates/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: devopsforai-aml-vg


steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'AzureResourceConnection'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(BASE_NAME)-AML-RG'
    location: $(LOCATION)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/environment_setup/arm-templates/cloud-environment.json'
    overrideParameters: '-baseName $(BASE_NAME) -location $(LOCATION)'
    deploymentMode: 'Incremental'
  displayName: 'Deploy MLOps resources to Azure'

  